// The try statement allows you to define a block of code to be tested for errors while it is being executed.
//The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.

console.log('pallab');

// console.log(lll)

try{
console.log(ppp)
}
catch(error){
    console.log('the error is ...............'+error)
}

setTimeout(() => {
    console.log('mondall');
}, 2000);